---
- hosts: all
  gather_facts: false
  tasks:
  block: "Deploy Appian"
    - name: "Place Appian systemd file"
      copy:
        src: appian-service.service
        dest: /etc/systemd/system/appian-service.service
    - name: "Enable Appian service"
      systemd:
        name: appian-service.service
        state: started
        enabled: yes
        daemon_reload: yes
  become: true
  become_user: root
