---
- hosts: all
  gather_facts: false
  tasks:
  - name: "Deploy Appian"
    block:
      - name: "Place Appian systemd file"
        copy:
          src: appian-svc.service
          dest: /etc/systemd/system/appian-svc.service
      - name: "Enable Appian service"
        systemd:
          name: appian-service.service
          state: started
          enabled: yes
          daemon_reload: yes
    become: true
    become_user: root
